version: '3.3'

services:
  api:
    container_name: auth-api
    build: 
      context: .
      dockerfile: ./build/local/Dockerfile
    command: 
      - /bin/sh
      - -c
      - |
        sh ./build/init.sh ${ADMIN_USER_PWD} ${ADMIN_USER_EMAIL}
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - db.sqlite3
    ports:
      - "8000:8000" 