version: '3.3'

services:
  api:
    build: .
    command: 
      - /bin/sh
      - -c
      - |
        sh init.sh ${ADMIN_USER_PWD} ${ADMIN_USER_EMAIL}
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - db.sqlite3
    ports:
      - "8000:8000"